# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c29ef0b498bfb8f00d1c91c03d9c0cc4"
name = "charmacy-carnival-app"
application_url = "https://charmasy-carnival.onrender.com"
embedded = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
scopes = "write_products,read_products,write_orders,read_orders"

[auth]
redirect_urls = [
  "https://charmasy-carnival.onrender.com/auth/callback",
  "https://charmasy-carnival.onrender.com/auth/shopify/callback",
  "https://charmasy-carnival.onrender.com/api/auth"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://charmasy-carnival.onrender.com/api/proxy"
subpath = "carnival-games"
prefix = "apps"
